### ISSUE TITLE
Widget caret for level 1 submenu item does not follow item text color

### ISSUE THREAD

**Issue by PowerGamer1** [kartik-v/yii2-dropdown-x#8]
When Bootstrap draws a caret (a triangle pointing down, see `.caret` class in Bootstrap) in collapsed navbar dropdown menu the caret has the same color as the menu item text containing this caret. When widget draws its caret (a triangle pointing right) for its submenus the caret does not have the same color as the menu item text. This can be seen for `.navbar-inverse` class (text color is gray, caret color is different (lighter)) and much more prominently for customized navbar colors, for example:

```CSS
.navbar-custom .navbar-nav > li > a {
    color: red;
}
@media (max-width: 767px) {
    .navbar-custom .navbar-nav .open .dropdown-menu > li > a {
        color: red;
    }
}
```
With the styles above all navbar menu text will be red and Bootstrap caret will also be red. Widget caret will not be red.
